
var YaneuraOu_sse42 = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(YaneuraOu_sse42) {
  YaneuraOu_sse42 = YaneuraOu_sse42 || {};


var c;c||(c=typeof YaneuraOu_sse42 !== 'undefined' ? YaneuraOu_sse42 : {});var aa,k;c.ready=new Promise(function(a,b){aa=a;k=b});
(function(){function a(){var g=e.shift();if(!b&&void 0!==g){if("quit"===g)return c.terminate();try{var l=c.ccall("usi_command","number",["string"],[g])}catch(p){l=0}l&&e.unshift(g);f=l?2*f:1;setTimeout(a,f)}}var b=!1,d=[];c.print=function(g){0===d.length?console.log(g):setTimeout(function(){for(var l=0;l<d.length;l++)d[l](g)})};c.addMessageListener=function(g){d.push(g)};c.removeMessageListener=function(g){g=d.indexOf(g);0<=g&&d.splice(g,1)};c.terminate=function(){b=!0};var e=[],f=1;c.postMessage=
function(g){e.push(g)};c.postRun=function(){c.postMessage=function(g){e.push(g);1===e.length&&a()};a()}})();var ba=Object.assign({},c),ca=[],t="./this.program",da=(a,b)=>{throw b;},ea="object"==typeof window,x="function"==typeof importScripts,A="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,B="",C,fa,ha;
if(A){B=x?require("path").dirname(B)+"/":__dirname+"/";var fs,ia;"function"===typeof require&&(fs=require("fs"),ia=require("path"));C=(a,b)=>{a=ia.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};ha=a=>{a=C(a,!0);a.buffer||(a=new Uint8Array(a));return a};fa=(a,b,d)=>{a=ia.normalize(a);fs.readFile(a,function(e,f){e?d(e):b(f.buffer)})};1<process.argv.length&&(t=process.argv[1].replace(/\\/g,"/"));ca=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof ja))throw a;
});process.on("unhandledRejection",function(a){throw a;});da=(a,b)=>{if(noExitRuntime)throw process.exitCode=a,b;b instanceof ja||D("exiting due to exception: "+b);process.exit(a)};c.inspect=function(){return"[Emscripten Module object]"}}else if(ea||x)x?B=self.location.href:"undefined"!=typeof document&&document.currentScript&&(B=document.currentScript.src),_scriptDir&&(B=_scriptDir),0!==B.indexOf("blob:")?B=B.substr(0,B.replace(/[?#].*/,"").lastIndexOf("/")+1):B="",C=a=>{var b=new XMLHttpRequest;
b.open("GET",a,!1);b.send(null);return b.responseText},x&&(ha=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),fa=(a,b,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?b(e.response):d()};e.onerror=d;e.send(null)};var ka=c.print||console.log.bind(console),D=c.printErr||console.warn.bind(console);Object.assign(c,ba);ba=null;c.arguments&&(ca=c.arguments);
c.thisProgram&&(t=c.thisProgram);c.quit&&(da=c.quit);var E;c.wasmBinary&&(E=c.wasmBinary);var noExitRuntime=c.noExitRuntime||!0;"object"!=typeof WebAssembly&&F("no native wasm support detected");var la,ma=!1,na="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function G(a,b){for(var d=b+NaN,e=b;a[e]&&!(e>=d);)++e;if(16<e-b&&a.buffer&&na)return na.decode(a.subarray(b,e));for(d="";b<e;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var l=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|l:(f&7)<<18|g<<12|l<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}
function H(a,b,d,e){if(!(0<e))return 0;var f=d;e=d+e-1;for(var g=0;g<a.length;++g){var l=a.charCodeAt(g);if(55296<=l&&57343>=l){var p=a.charCodeAt(++g);l=65536+((l&1023)<<10)|p&1023}if(127>=l){if(d>=e)break;b[d++]=l}else{if(2047>=l){if(d+1>=e)break;b[d++]=192|l>>6}else{if(65535>=l){if(d+2>=e)break;b[d++]=224|l>>12}else{if(d+3>=e)break;b[d++]=240|l>>18;b[d++]=128|l>>12&63}b[d++]=128|l>>6&63}b[d++]=128|l&63}}b[d]=0;return d-f}
function oa(a){for(var b=0,d=0;d<a.length;++d){var e=a.charCodeAt(d);127>=e?b++:2047>=e?b+=2:55296<=e&&57343>=e?(b+=4,++d):b+=3}return b}var pa,J,K,qa,L,M;function ra(){var a=la.buffer;pa=a;c.HEAP8=J=new Int8Array(a);c.HEAP16=qa=new Int16Array(a);c.HEAP32=L=new Int32Array(a);c.HEAPU8=K=new Uint8Array(a);c.HEAPU16=new Uint16Array(a);c.HEAPU32=M=new Uint32Array(a);c.HEAPF32=new Float32Array(a);c.HEAPF64=new Float64Array(a)}var sa=[],ta=[],ua=[],va=[];
function wa(){var a=c.preRun.shift();sa.unshift(a)}var N=0,xa=null,O=null;function ya(){N++;c.monitorRunDependencies&&c.monitorRunDependencies(N)}function za(){N--;c.monitorRunDependencies&&c.monitorRunDependencies(N);if(0==N&&(null!==xa&&(clearInterval(xa),xa=null),O)){var a=O;O=null;a()}}function F(a){if(c.onAbort)c.onAbort(a);a="Aborted("+a+")";D(a);ma=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");k(a);throw a;}
function Aa(){return P.startsWith("data:application/octet-stream;base64,")}var P;P="yaneuraou.wasm";if(!Aa()){var Ba=P;P=c.locateFile?c.locateFile(Ba,B):B+Ba}function Ca(){var a=P;try{if(a==P&&E)return new Uint8Array(E);if(ha)return ha(a);throw"both async and sync fetching of the wasm failed";}catch(b){F(b)}}
function Da(){return E||!ea&&!x||"function"!=typeof fetch?Promise.resolve().then(function(){return Ca()}):fetch(P,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+P+"'";return a.arrayBuffer()}).catch(function(){return Ca()})}var Q,Ea;function ja(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}function Fa(a){for(;0<a.length;)a.shift()(c)}
var Ga=(a,b)=>{for(var d=0,e=a.length-1;0<=e;e--){var f=a[e];"."===f?a.splice(e,1):".."===f?(a.splice(e,1),d++):d&&(a.splice(e,1),d--)}if(b)for(;d;d--)a.unshift("..");return a},R=a=>{var b="/"===a.charAt(0),d="/"===a.substr(-1);(a=Ga(a.split("/").filter(e=>!!e),!b).join("/"))||b||(a=".");a&&d&&(a+="/");return(b?"/":"")+a},Ha=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},S=a=>{if("/"===
a)return"/";a=R(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},Ia=(a,b)=>R(a+"/"+b);function Ja(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues){var a=new Uint8Array(1);return()=>{crypto.getRandomValues(a);return a[0]}}if(A)try{var b=require("crypto");return()=>b.randomBytes(1)[0]}catch(d){}return()=>F("randomDevice")}
function T(){for(var a="",b=!1,d=arguments.length-1;-1<=d&&!b;d--){b=0<=d?arguments[d]:U.cwd();if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Ga(a.split("/").filter(e=>!!e),!b).join("/");return(b?"/":"")+a||"."}
var Ka=(a,b)=>{function d(l){for(var p=0;p<l.length&&""===l[p];p++);for(var q=l.length-1;0<=q&&""===l[q];q--);return p>q?[]:l.slice(p,q-p+1)}a=T(a).substr(1);b=T(b).substr(1);a=d(a.split("/"));b=d(b.split("/"));for(var e=Math.min(a.length,b.length),f=e,g=0;g<e;g++)if(a[g]!==b[g]){f=g;break}e=[];for(g=f;g<a.length;g++)e.push("..");e=e.concat(b.slice(f));return e.join("/")};function La(a,b){var d=Array(oa(a)+1);a=H(a,d,0,d.length);b&&(d.length=a);return d}var Ma=[];
function Na(a,b){Ma[a]={input:[],output:[],U:b};U.Da(a,Oa)}
var Oa={open:function(a){var b=Ma[a.node.rdev];if(!b)throw new U.g(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.U.fsync(a.tty)},fsync:function(a){a.tty.U.fsync(a.tty)},read:function(a,b,d,e){if(!a.tty||!a.tty.U.Ra)throw new U.g(60);for(var f=0,g=0;g<e;g++){try{var l=a.tty.U.Ra(a.tty)}catch(p){throw new U.g(29);}if(void 0===l&&0===f)throw new U.g(6);if(null===l||void 0===l)break;f++;b[d+g]=l}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,d,e){if(!a.tty||!a.tty.U.Aa)throw new U.g(60);
try{for(var f=0;f<e;f++)a.tty.U.Aa(a.tty,b[d+f])}catch(g){throw new U.g(29);}e&&(a.node.timestamp=Date.now());return f}},Pa={Ra:function(a){if(!a.input.length){var b=null;if(A){var d=Buffer.alloc(256),e=0;try{e=fs.readSync(process.stdin.fd,d,0,256,-1)}catch(f){if(f.toString().includes("EOF"))e=0;else throw f;}0<e?b=d.slice(0,e).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=
readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=La(b,!0)}return a.input.shift()},Aa:function(a,b){null===b||10===b?(ka(G(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync:function(a){a.output&&0<a.output.length&&(ka(G(a.output,0)),a.output=[])}},Qa={Aa:function(a,b){null===b||10===b?(D(G(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync:function(a){a.output&&0<a.output.length&&(D(G(a.output,0)),a.output=[])}},V={F:null,o:function(){return V.createNode(null,"/",16895,0)},createNode:function(a,
b,d,e){if(U.qb(d)||U.isFIFO(d))throw new U.g(63);V.F||(V.F={dir:{node:{B:V.h.B,u:V.h.u,lookup:V.h.lookup,J:V.h.J,rename:V.h.rename,unlink:V.h.unlink,rmdir:V.h.rmdir,readdir:V.h.readdir,symlink:V.h.symlink},stream:{C:V.j.C}},file:{node:{B:V.h.B,u:V.h.u},stream:{C:V.j.C,read:V.j.read,write:V.j.write,W:V.j.W,T:V.j.T,ba:V.j.ba}},link:{node:{B:V.h.B,u:V.h.u,readlink:V.h.readlink},stream:{}},Ia:{node:{B:V.h.B,u:V.h.u},stream:U.eb}});d=U.createNode(a,b,d,e);U.s(d.mode)?(d.h=V.F.dir.node,d.j=V.F.dir.stream,
d.i={}):U.isFile(d.mode)?(d.h=V.F.file.node,d.j=V.F.file.stream,d.m=0,d.i=null):U.Z(d.mode)?(d.h=V.F.link.node,d.j=V.F.link.stream):U.fa(d.mode)&&(d.h=V.F.Ia.node,d.j=V.F.Ia.stream);d.timestamp=Date.now();a&&(a.i[b]=d,a.timestamp=d.timestamp);return d},Ob:function(a){return a.i?a.i.subarray?a.i.subarray(0,a.m):new Uint8Array(a.i):new Uint8Array(0)},Oa:function(a,b){var d=a.i?a.i.length:0;d>=b||(b=Math.max(b,d*(1048576>d?2:1.125)>>>0),0!=d&&(b=Math.max(b,256)),d=a.i,a.i=new Uint8Array(b),0<a.m&&a.i.set(d.subarray(0,
a.m),0))},Ab:function(a,b){if(a.m!=b)if(0==b)a.i=null,a.m=0;else{var d=a.i;a.i=new Uint8Array(b);d&&a.i.set(d.subarray(0,Math.min(b,a.m)));a.m=b}},h:{B:function(a){var b={};b.dev=U.fa(a.mode)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;U.s(a.mode)?b.size=4096:U.isFile(a.mode)?b.size=a.m:U.Z(a.mode)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.bb=4096;b.blocks=Math.ceil(b.size/b.bb);return b},u:function(a,
b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&V.Ab(a,b.size)},lookup:function(){throw U.qa[44];},J:function(a,b,d,e){return V.createNode(a,b,d,e)},rename:function(a,b,d){if(U.s(a.mode)){try{var e=U.I(b,d)}catch(g){}if(e)for(var f in e.i)throw new U.g(55);}delete a.parent.i[a.name];a.parent.timestamp=Date.now();a.name=d;b.i[d]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.i[b];a.timestamp=Date.now()},rmdir:function(a,
b){var d=U.I(a,b),e;for(e in d.i)throw new U.g(55);delete a.i[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],d;for(d in a.i)a.i.hasOwnProperty(d)&&b.push(d);return b},symlink:function(a,b,d){a=V.createNode(a,b,41471,0);a.link=d;return a},readlink:function(a){if(!U.Z(a.mode))throw new U.g(28);return a.link}},j:{read:function(a,b,d,e,f){var g=a.node.i;if(f>=a.node.m)return 0;a=Math.min(a.node.m-f,e);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),d);else for(e=0;e<a;e++)b[d+e]=g[f+e];return a},
write:function(a,b,d,e,f,g){b.buffer===J.buffer&&(g=!1);if(!e)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.i||a.i.subarray)){if(g)return a.i=b.subarray(d,d+e),a.m=e;if(0===a.m&&0===f)return a.i=b.slice(d,d+e),a.m=e;if(f+e<=a.m)return a.i.set(b.subarray(d,d+e),f),e}V.Oa(a,f+e);if(a.i.subarray&&b.subarray)a.i.set(b.subarray(d,d+e),f);else for(g=0;g<e;g++)a.i[f+g]=b[d+g];a.m=Math.max(a.m,f+e);return e},C:function(a,b,d){1===d?b+=a.position:2===d&&U.isFile(a.node.mode)&&(b+=a.node.m);if(0>
b)throw new U.g(28);return b},W:function(a,b,d){V.Oa(a.node,b+d);a.node.m=Math.max(a.node.m,b+d)},T:function(a,b,d,e,f){if(!U.isFile(a.node.mode))throw new U.g(43);a=a.node.i;if(f&2||a.buffer!==pa){if(0<d||d+b<a.length)a.subarray?a=a.subarray(d,d+b):a=Array.prototype.slice.call(a,d,d+b);d=!0;F();b=void 0;if(!b)throw new U.g(48);J.set(a,b)}else d=!1,b=a.byteOffset;return{Vb:b,Ib:d}},ba:function(a,b,d,e){V.j.write(a,b,0,e,d,!1);return 0}}};
function Ra(a,b,d){var e="al "+a;fa(a,f=>{f||F('Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(f));e&&za()},()=>{if(d)d();else throw'Loading data file "'+a+'" failed.';});e&&ya()}
var U={root:null,aa:[],Ma:{},streams:[],vb:1,D:null,La:"/",ua:!1,Va:!0,g:null,qa:{},mb:null,ja:0,l:(a,b={})=>{a=T(U.cwd(),a);if(!a)return{path:"",node:null};b=Object.assign({oa:!0,Ca:0},b);if(8<b.Ca)throw new U.g(32);a=Ga(a.split("/").filter(l=>!!l),!1);for(var d=U.root,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;d=U.I(d,a[f]);e=R(e+"/"+a[f]);U.M(d)&&(!g||g&&b.oa)&&(d=d.$.root);if(!g||b.A)for(g=0;U.Z(d.mode);)if(d=U.readlink(e),e=T(Ha(e),d),d=U.l(e,{Ca:b.Ca+1}).node,40<g++)throw new U.g(32);
}return{path:e,node:d}},L:a=>{for(var b;;){if(U.ga(a))return a=a.o.Wa,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},ta:(a,b)=>{for(var d=0,e=0;e<b.length;e++)d=(d<<5)-d+b.charCodeAt(e)|0;return(a+d>>>0)%U.D.length},Ta:a=>{var b=U.ta(a.parent.id,a.name);a.O=U.D[b];U.D[b]=a},Ua:a=>{var b=U.ta(a.parent.id,a.name);if(U.D[b]===a)U.D[b]=a.O;else for(b=U.D[b];b;){if(b.O===a){b.O=a.O;break}b=b.O}},I:(a,b)=>{var d=U.sb(a);if(d)throw new U.g(d,a);for(d=U.D[U.ta(a.id,b)];d;d=d.O){var e=
d.name;if(d.parent.id===a.id&&e===b)return d}return U.lookup(a,b)},createNode:(a,b,d,e)=>{a=new U.Ya(a,b,d,e);U.Ta(a);return a},na:a=>{U.Ua(a)},ga:a=>a===a.parent,M:a=>!!a.$,isFile:a=>32768===(a&61440),s:a=>16384===(a&61440),Z:a=>40960===(a&61440),fa:a=>8192===(a&61440),qb:a=>24576===(a&61440),isFIFO:a=>4096===(a&61440),isSocket:a=>49152===(a&49152),nb:{r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},ub:a=>{var b=U.nb[a];if("undefined"==typeof b)throw Error("Unknown file open mode: "+a);return b},Pa:a=>
{var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},P:(a,b)=>{if(U.Va)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},sb:a=>{var b=U.P(a,"x");return b?b:a.h.lookup?0:2},za:(a,b)=>{try{return U.I(a,b),20}catch(d){}return U.P(a,"wx")},ha:(a,b,d)=>{try{var e=U.I(a,b)}catch(f){return f.v}if(a=U.P(a,"wx"))return a;if(d){if(!U.s(e.mode))return 54;if(U.ga(e)||U.L(e)===U.cwd())return 10}else if(U.s(e.mode))return 31;
return 0},tb:(a,b)=>a?U.Z(a.mode)?32:U.s(a.mode)&&("r"!==U.Pa(b)||b&512)?31:U.P(a,U.Pa(b)):44,Za:4096,wb:(a=0,b=U.Za)=>{for(;a<=b;a++)if(!U.streams[a])return a;throw new U.g(33);},X:a=>U.streams[a],Ka:(a,b,d)=>{U.da||(U.da=function(){this.H={}},U.da.prototype={},Object.defineProperties(U.da.prototype,{object:{get:function(){return this.node},set:function(e){this.node=e}},flags:{get:function(){return this.H.flags},set:function(e){this.H.flags=e}},position:{get:function(){return this.H.position},set:function(e){this.H.position=
e}}}));a=Object.assign(new U.da,a);b=U.wb(b,d);a.fd=b;return U.streams[b]=a},fb:a=>{U.streams[a]=null},eb:{open:a=>{a.j=U.ob(a.node.rdev).j;a.j.open&&a.j.open(a)},C:()=>{throw new U.g(70);}},ya:a=>a>>8,Rb:a=>a&255,N:(a,b)=>a<<8|b,Da:(a,b)=>{U.Ma[a]={j:b}},ob:a=>U.Ma[a],Qa:a=>{var b=[];for(a=[a];a.length;){var d=a.pop();b.push(d);a.push.apply(a,d.aa)}return b},Xa:(a,b)=>{function d(l){U.ja--;return b(l)}function e(l){if(l){if(!e.lb)return e.lb=!0,d(l)}else++g>=f.length&&d(null)}"function"==typeof a&&
(b=a,a=!1);U.ja++;1<U.ja&&D("warning: "+U.ja+" FS.syncfs operations in flight at once, probably just doing extra work");var f=U.Qa(U.root.o),g=0;f.forEach(l=>{if(!l.type.Xa)return e(null);l.type.Xa(l,a,e)})},o:(a,b,d)=>{var e="/"===d,f=!d;if(e&&U.root)throw new U.g(10);if(!e&&!f){var g=U.l(d,{oa:!1});d=g.path;g=g.node;if(U.M(g))throw new U.g(10);if(!U.s(g.mode))throw new U.g(54);}b={type:a,Ub:b,Wa:d,aa:[]};a=a.o(b);a.o=b;b.root=a;e?U.root=a:g&&(g.$=b,g.o&&g.o.aa.push(b));return a},Zb:a=>{a=U.l(a,
{oa:!1});if(!U.M(a.node))throw new U.g(28);a=a.node;var b=a.$,d=U.Qa(b);Object.keys(U.D).forEach(e=>{for(e=U.D[e];e;){var f=e.O;d.includes(e.o)&&U.na(e);e=f}});a.$=null;a.o.aa.splice(a.o.aa.indexOf(b),1)},lookup:(a,b)=>a.h.lookup(a,b),J:(a,b,d)=>{var e=U.l(a,{parent:!0}).node;a=S(a);if(!a||"."===a||".."===a)throw new U.g(28);var f=U.za(e,a);if(f)throw new U.g(f);if(!e.h.J)throw new U.g(63);return e.h.J(e,a,b,d)},create:(a,b)=>U.J(a,(void 0!==b?b:438)&4095|32768,0),mkdir:(a,b)=>U.J(a,(void 0!==b?b:
511)&1023|16384,0),Sb:(a,b)=>{a=a.split("/");for(var d="",e=0;e<a.length;++e)if(a[e]){d+="/"+a[e];try{U.mkdir(d,b)}catch(f){if(20!=f.v)throw f;}}},ia:(a,b,d)=>{"undefined"==typeof d&&(d=b,b=438);return U.J(a,b|8192,d)},symlink:(a,b)=>{if(!T(a))throw new U.g(44);var d=U.l(b,{parent:!0}).node;if(!d)throw new U.g(44);b=S(b);var e=U.za(d,b);if(e)throw new U.g(e);if(!d.h.symlink)throw new U.g(63);return d.h.symlink(d,b,a)},rename:(a,b)=>{var d=Ha(a),e=Ha(b),f=S(a),g=S(b);var l=U.l(a,{parent:!0});var p=
l.node;l=U.l(b,{parent:!0});l=l.node;if(!p||!l)throw new U.g(44);if(p.o!==l.o)throw new U.g(75);var q=U.I(p,f);a=Ka(a,e);if("."!==a.charAt(0))throw new U.g(28);a=Ka(b,d);if("."!==a.charAt(0))throw new U.g(55);try{var m=U.I(l,g)}catch(n){}if(q!==m){b=U.s(q.mode);if(f=U.ha(p,f,b))throw new U.g(f);if(f=m?U.ha(l,g,b):U.za(l,g))throw new U.g(f);if(!p.h.rename)throw new U.g(63);if(U.M(q)||m&&U.M(m))throw new U.g(10);if(l!==p&&(f=U.P(p,"w")))throw new U.g(f);U.Ua(q);try{p.h.rename(q,l,g)}catch(n){throw n;
}finally{U.Ta(q)}}},rmdir:a=>{var b=U.l(a,{parent:!0}).node;a=S(a);var d=U.I(b,a),e=U.ha(b,a,!0);if(e)throw new U.g(e);if(!b.h.rmdir)throw new U.g(63);if(U.M(d))throw new U.g(10);b.h.rmdir(b,a);U.na(d)},readdir:a=>{a=U.l(a,{A:!0}).node;if(!a.h.readdir)throw new U.g(54);return a.h.readdir(a)},unlink:a=>{var b=U.l(a,{parent:!0}).node;if(!b)throw new U.g(44);a=S(a);var d=U.I(b,a),e=U.ha(b,a,!1);if(e)throw new U.g(e);if(!b.h.unlink)throw new U.g(63);if(U.M(d))throw new U.g(10);b.h.unlink(b,a);U.na(d)},
readlink:a=>{a=U.l(a).node;if(!a)throw new U.g(44);if(!a.h.readlink)throw new U.g(28);return T(U.L(a.parent),a.h.readlink(a))},stat:(a,b)=>{a=U.l(a,{A:!b}).node;if(!a)throw new U.g(44);if(!a.h.B)throw new U.g(63);return a.h.B(a)},lstat:a=>U.stat(a,!0),chmod:(a,b,d)=>{a="string"==typeof a?U.l(a,{A:!d}).node:a;if(!a.h.u)throw new U.g(63);a.h.u(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},lchmod:(a,b)=>{U.chmod(a,b,!0)},fchmod:(a,b)=>{a=U.X(a);if(!a)throw new U.g(8);U.chmod(a.node,b)},chown:(a,
b,d,e)=>{a="string"==typeof a?U.l(a,{A:!e}).node:a;if(!a.h.u)throw new U.g(63);a.h.u(a,{timestamp:Date.now()})},lchown:(a,b,d)=>{U.chown(a,b,d,!0)},fchown:(a,b,d)=>{a=U.X(a);if(!a)throw new U.g(8);U.chown(a.node,b,d)},truncate:(a,b)=>{if(0>b)throw new U.g(28);a="string"==typeof a?U.l(a,{A:!0}).node:a;if(!a.h.u)throw new U.g(63);if(U.s(a.mode))throw new U.g(31);if(!U.isFile(a.mode))throw new U.g(28);var d=U.P(a,"w");if(d)throw new U.g(d);a.h.u(a,{size:b,timestamp:Date.now()})},Nb:(a,b)=>{a=U.X(a);
if(!a)throw new U.g(8);if(0===(a.flags&2097155))throw new U.g(28);U.truncate(a.node,b)},$b:(a,b,d)=>{a=U.l(a,{A:!0}).node;a.h.u(a,{timestamp:Math.max(b,d)})},open:(a,b,d)=>{if(""===a)throw new U.g(44);b="string"==typeof b?U.ub(b):b;d=b&64?("undefined"==typeof d?438:d)&4095|32768:0;if("object"==typeof a)var e=a;else{a=R(a);try{e=U.l(a,{A:!(b&131072)}).node}catch(g){}}var f=!1;if(b&64)if(e){if(b&128)throw new U.g(20);}else e=U.J(a,d,0),f=!0;if(!e)throw new U.g(44);U.fa(e.mode)&&(b&=-513);if(b&65536&&
!U.s(e.mode))throw new U.g(54);if(!f&&(d=U.tb(e,b)))throw new U.g(d);b&512&&!f&&U.truncate(e,0);b&=-131713;e=U.Ka({node:e,path:U.L(e),flags:b,seekable:!0,position:0,j:e.j,Hb:[],error:!1});e.j.open&&e.j.open(e);!c.logReadFiles||b&1||(U.Ba||(U.Ba={}),a in U.Ba||(U.Ba[a]=1));return e},close:a=>{if(U.Y(a))throw new U.g(8);a.sa&&(a.sa=null);try{a.j.close&&a.j.close(a)}catch(b){throw b;}finally{U.fb(a.fd)}a.fd=null},Y:a=>null===a.fd,C:(a,b,d)=>{if(U.Y(a))throw new U.g(8);if(!a.seekable||!a.j.C)throw new U.g(70);
if(0!=d&&1!=d&&2!=d)throw new U.g(28);a.position=a.j.C(a,b,d);a.Hb=[];return a.position},read:(a,b,d,e,f)=>{if(0>e||0>f)throw new U.g(28);if(U.Y(a))throw new U.g(8);if(1===(a.flags&2097155))throw new U.g(8);if(U.s(a.node.mode))throw new U.g(31);if(!a.j.read)throw new U.g(28);var g="undefined"!=typeof f;if(!g)f=a.position;else if(!a.seekable)throw new U.g(70);b=a.j.read(a,b,d,e,f);g||(a.position+=b);return b},write:(a,b,d,e,f,g)=>{if(0>e||0>f)throw new U.g(28);if(U.Y(a))throw new U.g(8);if(0===(a.flags&
2097155))throw new U.g(8);if(U.s(a.node.mode))throw new U.g(31);if(!a.j.write)throw new U.g(28);a.seekable&&a.flags&1024&&U.C(a,0,2);var l="undefined"!=typeof f;if(!l)f=a.position;else if(!a.seekable)throw new U.g(70);b=a.j.write(a,b,d,e,f,g);l||(a.position+=b);return b},W:(a,b,d)=>{if(U.Y(a))throw new U.g(8);if(0>b||0>=d)throw new U.g(28);if(0===(a.flags&2097155))throw new U.g(8);if(!U.isFile(a.node.mode)&&!U.s(a.node.mode))throw new U.g(43);if(!a.j.W)throw new U.g(138);a.j.W(a,b,d)},T:(a,b,d,e,
f)=>{if(0!==(e&2)&&0===(f&2)&&2!==(a.flags&2097155))throw new U.g(2);if(1===(a.flags&2097155))throw new U.g(2);if(!a.j.T)throw new U.g(43);return a.j.T(a,b,d,e,f)},ba:(a,b,d,e,f)=>a.j.ba?a.j.ba(a,b,d,e,f):0,Tb:()=>0,va:(a,b,d)=>{if(!a.j.va)throw new U.g(59);return a.j.va(a,b,d)},readFile:(a,b={})=>{b.flags=b.flags||0;b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error('Invalid encoding type "'+b.encoding+'"');var d,e=U.open(a,b.flags);a=U.stat(a).size;var f=new Uint8Array(a);
U.read(e,f,0,a,0);"utf8"===b.encoding?d=G(f,0):"binary"===b.encoding&&(d=f);U.close(e);return d},writeFile:(a,b,d={})=>{d.flags=d.flags||577;a=U.open(a,d.flags,d.mode);if("string"==typeof b){var e=new Uint8Array(oa(b)+1);b=H(b,e,0,e.length);U.write(a,e,0,b,void 0,d.cb)}else if(ArrayBuffer.isView(b))U.write(a,b,0,b.byteLength,void 0,d.cb);else throw Error("Unsupported data type");U.close(a)},cwd:()=>U.La,chdir:a=>{a=U.l(a,{A:!0});if(null===a.node)throw new U.g(44);if(!U.s(a.node.mode))throw new U.g(54);
var b=U.P(a.node,"x");if(b)throw new U.g(b);U.La=a.path},hb:()=>{U.mkdir("/tmp");U.mkdir("/home");U.mkdir("/home/web_user")},gb:()=>{U.mkdir("/dev");U.Da(U.N(1,3),{read:()=>0,write:(b,d,e,f)=>f});U.ia("/dev/null",U.N(1,3));Na(U.N(5,0),Pa);Na(U.N(6,0),Qa);U.ia("/dev/tty",U.N(5,0));U.ia("/dev/tty1",U.N(6,0));var a=Ja();U.K("/dev","random",a);U.K("/dev","urandom",a);U.mkdir("/dev/shm");U.mkdir("/dev/shm/tmp")},jb:()=>{U.mkdir("/proc");var a=U.mkdir("/proc/self");U.mkdir("/proc/self/fd");U.o({o:()=>{var b=
U.createNode(a,"fd",16895,73);b.h={lookup:(d,e)=>{var f=U.X(+e);if(!f)throw new U.g(8);d={parent:null,o:{Wa:"fake"},h:{readlink:()=>f.path}};return d.parent=d}};return b}},{},"/proc/self/fd")},kb:()=>{c.stdin?U.K("/dev","stdin",c.stdin):U.symlink("/dev/tty","/dev/stdin");c.stdout?U.K("/dev","stdout",null,c.stdout):U.symlink("/dev/tty","/dev/stdout");c.stderr?U.K("/dev","stderr",null,c.stderr):U.symlink("/dev/tty1","/dev/stderr");U.open("/dev/stdin",0);U.open("/dev/stdout",1);U.open("/dev/stderr",
1)},Na:()=>{U.g||(U.g=function(a,b){this.node=b;this.Bb=function(d){this.v=d};this.Bb(a);this.message="FS error"},U.g.prototype=Error(),U.g.prototype.constructor=U.g,[44].forEach(a=>{U.qa[a]=new U.g(a);U.qa[a].stack="<generic error, no stack>"}))},Cb:()=>{U.Na();U.D=Array(4096);U.o(V,{},"/");U.hb();U.gb();U.jb();U.mb={MEMFS:V}},ea:(a,b,d)=>{U.ea.ua=!0;U.Na();c.stdin=a||c.stdin;c.stdout=b||c.stdout;c.stderr=d||c.stderr;U.kb()},Wb:()=>{U.ea.ua=!1;for(var a=0;a<U.streams.length;a++){var b=U.streams[a];
b&&U.close(b)}},ra:(a,b)=>{var d=0;a&&(d|=365);b&&(d|=146);return d},Mb:(a,b)=>{a=U.ma(a,b);return a.exists?a.object:null},ma:(a,b)=>{try{var d=U.l(a,{A:!b});a=d.path}catch(f){}var e={ga:!1,exists:!1,error:0,name:null,path:null,object:null,xb:!1,zb:null,yb:null};try{d=U.l(a,{parent:!0}),e.xb=!0,e.zb=d.path,e.yb=d.node,e.name=S(a),d=U.l(a,{A:!b}),e.exists=!0,e.path=d.path,e.object=d.node,e.name=d.node.name,e.ga="/"===d.path}catch(f){e.error=f.v}return e},Kb:(a,b)=>{a="string"==typeof a?a:U.L(a);for(b=
b.split("/").reverse();b.length;){var d=b.pop();if(d){var e=R(a+"/"+d);try{U.mkdir(e)}catch(f){}a=e}}return e},ib:(a,b,d,e,f)=>{a="string"==typeof a?a:U.L(a);b=R(a+"/"+b);return U.create(b,U.ra(e,f))},Ja:(a,b,d,e,f,g)=>{var l=b;a&&(a="string"==typeof a?a:U.L(a),l=b?R(a+"/"+b):a);a=U.ra(e,f);l=U.create(l,a);if(d){if("string"==typeof d){b=Array(d.length);e=0;for(f=d.length;e<f;++e)b[e]=d.charCodeAt(e);d=b}U.chmod(l,a|146);b=U.open(l,577);U.write(b,d,0,d.length,0,g);U.close(b);U.chmod(l,a)}return l},
K:(a,b,d,e)=>{a=Ia("string"==typeof a?a:U.L(a),b);b=U.ra(!!d,!!e);U.K.ya||(U.K.ya=64);var f=U.N(U.K.ya++,0);U.Da(f,{open:g=>{g.seekable=!1},close:()=>{e&&e.buffer&&e.buffer.length&&e(10)},read:(g,l,p,q)=>{for(var m=0,n=0;n<q;n++){try{var v=d()}catch(w){throw new U.g(29);}if(void 0===v&&0===m)throw new U.g(6);if(null===v||void 0===v)break;m++;l[p+n]=v}m&&(g.node.timestamp=Date.now());return m},write:(g,l,p,q)=>{for(var m=0;m<q;m++)try{e(l[p+m])}catch(n){throw new U.g(29);}q&&(g.node.timestamp=Date.now());
return m}});return U.ia(a,b,f)},pa:a=>{if(a.wa||a.rb||a.link||a.i)return!0;if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(C)try{a.i=La(C(a.url),!0),a.m=a.i.length}catch(b){throw new U.g(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");},Jb:(a,b,d,e,f)=>{function g(){this.xa=!1;
this.H=[]}g.prototype.get=function(m){if(!(m>this.length-1||0>m)){var n=m%this.chunkSize;return this.Sa(m/this.chunkSize|0)[n]}};g.prototype.pb=function(m){this.Sa=m};g.prototype.Ha=function(){var m=new XMLHttpRequest;m.open("HEAD",d,!1);m.send(null);if(!(200<=m.status&&300>m.status||304===m.status))throw Error("Couldn't load "+d+". Status: "+m.status);var n=Number(m.getResponseHeader("Content-length")),v,w=(v=m.getResponseHeader("Accept-Ranges"))&&"bytes"===v;m=(v=m.getResponseHeader("Content-Encoding"))&&
"gzip"===v;var h=1048576;w||(h=n);var r=this;r.pb(u=>{var y=u*h,I=(u+1)*h-1;I=Math.min(I,n-1);if("undefined"==typeof r.H[u]){var hb=r.H;if(y>I)throw Error("invalid range ("+y+", "+I+") or no bytes requested!");if(I>n-1)throw Error("only "+n+" bytes available! programmer error!");var z=new XMLHttpRequest;z.open("GET",d,!1);n!==h&&z.setRequestHeader("Range","bytes="+y+"-"+I);z.responseType="arraybuffer";z.overrideMimeType&&z.overrideMimeType("text/plain; charset=x-user-defined");z.send(null);if(!(200<=
z.status&&300>z.status||304===z.status))throw Error("Couldn't load "+d+". Status: "+z.status);y=void 0!==z.response?new Uint8Array(z.response||[]):La(z.responseText||"",!0);hb[u]=y}if("undefined"==typeof r.H[u])throw Error("doXHR failed!");return r.H[u]});if(m||!n)h=n=1,h=n=this.Sa(0).length,ka("LazyFiles on gzip forces download of the whole file when length is accessed");this.ab=n;this.$a=h;this.xa=!0};if("undefined"!=typeof XMLHttpRequest){if(!x)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";
var l=new g;Object.defineProperties(l,{length:{get:function(){this.xa||this.Ha();return this.ab}},chunkSize:{get:function(){this.xa||this.Ha();return this.$a}}});l={wa:!1,i:l}}else l={wa:!1,url:d};var p=U.ib(a,b,l,e,f);l.i?p.i=l.i:l.url&&(p.i=null,p.url=l.url);Object.defineProperties(p,{m:{get:function(){return this.i.length}}});var q={};Object.keys(p.j).forEach(m=>{var n=p.j[m];q[m]=function(){U.pa(p);return n.apply(null,arguments)}});q.read=(m,n,v,w,h)=>{U.pa(p);m=m.node.i;if(h>=m.length)n=0;else{w=
Math.min(m.length-h,w);if(m.slice)for(var r=0;r<w;r++)n[v+r]=m[h+r];else for(r=0;r<w;r++)n[v+r]=m.get(h+r);n=w}return n};q.T=()=>{U.pa(p);F();throw new U.g(48);};p.j=q;return p},Lb:(a,b,d,e,f,g,l,p,q,m)=>{function n(w){function h(r){m&&m();p||U.Ja(a,b,r,e,f,q);g&&g();za()}Sa.Pb(w,v,h,()=>{l&&l();za()})||h(w)}var v=b?T(R(a+"/"+b)):a;ya();"string"==typeof d?Ra(d,w=>n(w),l):n(d)},indexedDB:()=>window.indexedDB||window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB,Fa:()=>"EM_FS_"+window.location.pathname,
Ga:20,V:"FILE_DATA",Xb:(a,b,d)=>{b=b||(()=>{});d=d||(()=>{});var e=U.indexedDB();try{var f=e.open(U.Fa(),U.Ga)}catch(g){return d(g)}f.onupgradeneeded=()=>{ka("creating db");f.result.createObjectStore(U.V)};f.onsuccess=()=>{var g=f.result.transaction([U.V],"readwrite"),l=g.objectStore(U.V),p=0,q=0,m=a.length;a.forEach(n=>{n=l.put(U.ma(n).object.i,n);n.onsuccess=()=>{p++;p+q==m&&(0==q?b():d())};n.onerror=()=>{q++;p+q==m&&(0==q?b():d())}});g.onerror=d};f.onerror=d},Qb:(a,b,d)=>{b=b||(()=>{});d=d||(()=>
{});var e=U.indexedDB();try{var f=e.open(U.Fa(),U.Ga)}catch(g){return d(g)}f.onupgradeneeded=d;f.onsuccess=()=>{var g=f.result;try{var l=g.transaction([U.V],"readonly")}catch(v){d(v);return}var p=l.objectStore(U.V),q=0,m=0,n=a.length;a.forEach(v=>{var w=p.get(v);w.onsuccess=()=>{U.ma(v).exists&&U.unlink(v);U.Ja(Ha(v),S(v),w.result,!0,!0,!0);q++;q+m==n&&(0==m?b():d())};w.onerror=()=>{m++;q+m==n&&(0==m?b():d())}});l.onerror=d};f.onerror=d}},W=void 0;function X(){W+=4;return L[W-4>>2]}
function Y(a){a=U.X(a);if(!a)throw new U.g(8);return a}var Ta;Ta=A?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:()=>performance.now();var Ua={};function Va(){if(!Wa){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:t||"./this.program"},b;for(b in Ua)void 0===Ua[b]?delete a[b]:a[b]=Ua[b];var d=[];for(b in a)d.push(b+"="+a[b]);Wa=d}return Wa}var Wa;
function Xa(a){if(!noExitRuntime){if(c.onExit)c.onExit(a);ma=!0}da(a,new ja(a))}function Ya(a){return 0===a%4&&(0!==a%100||0===a%400)}var Za=[31,29,31,30,31,30,31,31,30,31,30,31],$a=[31,28,31,30,31,30,31,31,30,31,30,31];
function ab(a,b,d,e){function f(h,r,u){for(h="number"==typeof h?h.toString():h||"";h.length<r;)h=u[0]+h;return h}function g(h,r){return f(h,r,"0")}function l(h,r){function u(I){return 0>I?-1:0<I?1:0}var y;0===(y=u(h.getFullYear()-r.getFullYear()))&&0===(y=u(h.getMonth()-r.getMonth()))&&(y=u(h.getDate()-r.getDate()));return y}function p(h){switch(h.getDay()){case 0:return new Date(h.getFullYear()-1,11,29);case 1:return h;case 2:return new Date(h.getFullYear(),0,3);case 3:return new Date(h.getFullYear(),
0,2);case 4:return new Date(h.getFullYear(),0,1);case 5:return new Date(h.getFullYear()-1,11,31);case 6:return new Date(h.getFullYear()-1,11,30)}}function q(h){var r=h.R;for(h=new Date((new Date(h.S+1900,0,1)).getTime());0<r;){var u=h.getMonth(),y=(Ya(h.getFullYear())?Za:$a)[u];if(r>y-h.getDate())r-=y-h.getDate()+1,h.setDate(1),11>u?h.setMonth(u+1):(h.setMonth(0),h.setFullYear(h.getFullYear()+1));else{h.setDate(h.getDate()+r);break}}u=new Date(h.getFullYear()+1,0,4);r=p(new Date(h.getFullYear(),0,
4));u=p(u);return 0>=l(r,h)?0>=l(u,h)?h.getFullYear()+1:h.getFullYear():h.getFullYear()-1}var m=L[e+40>>2];e={Fb:L[e>>2],Eb:L[e+4>>2],ka:L[e+8>>2],Ea:L[e+12>>2],la:L[e+16>>2],S:L[e+20>>2],G:L[e+24>>2],R:L[e+28>>2],Yb:L[e+32>>2],Db:L[e+36>>2],Gb:m?m?G(K,m):"":""};d=d?G(K,d):"";m={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y",
"%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var n in m)d=d.replace(new RegExp(n,"g"),m[n]);var v="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),w="January February March April May June July August September October November December".split(" ");m={"%a":function(h){return v[h.G].substring(0,3)},"%A":function(h){return v[h.G]},"%b":function(h){return w[h.la].substring(0,3)},
"%B":function(h){return w[h.la]},"%C":function(h){return g((h.S+1900)/100|0,2)},"%d":function(h){return g(h.Ea,2)},"%e":function(h){return f(h.Ea,2," ")},"%g":function(h){return q(h).toString().substring(2)},"%G":function(h){return q(h)},"%H":function(h){return g(h.ka,2)},"%I":function(h){h=h.ka;0==h?h=12:12<h&&(h-=12);return g(h,2)},"%j":function(h){for(var r=0,u=0;u<=h.la-1;r+=(Ya(h.S+1900)?Za:$a)[u++]);return g(h.Ea+r,3)},"%m":function(h){return g(h.la+1,2)},"%M":function(h){return g(h.Eb,2)},
"%n":function(){return"\n"},"%p":function(h){return 0<=h.ka&&12>h.ka?"AM":"PM"},"%S":function(h){return g(h.Fb,2)},"%t":function(){return"\t"},"%u":function(h){return h.G||7},"%U":function(h){return g(Math.floor((h.R+7-h.G)/7),2)},"%V":function(h){var r=Math.floor((h.R+7-(h.G+6)%7)/7);2>=(h.G+371-h.R-2)%7&&r++;if(r)53==r&&(u=(h.G+371-h.R)%7,4==u||3==u&&Ya(h.S)||(r=1));else{r=52;var u=(h.G+7-h.R-1)%7;(4==u||5==u&&Ya(h.S%400-1))&&r++}return g(r,2)},"%w":function(h){return h.G},"%W":function(h){return g(Math.floor((h.R+
7-(h.G+6)%7)/7),2)},"%y":function(h){return(h.S+1900).toString().substring(2)},"%Y":function(h){return h.S+1900},"%z":function(h){h=h.Db;var r=0<=h;h=Math.abs(h)/60;return(r?"+":"-")+String("0000"+(h/60*100+h%60)).slice(-4)},"%Z":function(h){return h.Gb},"%%":function(){return"%"}};d=d.replace(/%%/g,"\x00\x00");for(n in m)d.includes(n)&&(d=d.replace(new RegExp(n,"g"),m[n](e)));d=d.replace(/\0\0/g,"%");n=La(d,!1);if(n.length>b)return 0;J.set(n,a);return n.length-1}
function bb(a,b,d,e){a||(a=this);this.parent=a;this.o=a.o;this.$=null;this.id=U.vb++;this.name=b;this.mode=d;this.h={};this.j={};this.rdev=e}Object.defineProperties(bb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},rb:{get:function(){return U.s(this.mode)}},wa:{get:function(){return U.fa(this.mode)}}});U.Ya=bb;U.Cb();
var Sa,db={__syscall_fcntl64:function(a,b,d){W=d;try{var e=Y(a);switch(b){case 0:var f=X();return 0>f?-28:U.Ka(e,f).fd;case 1:case 2:return 0;case 3:return e.flags;case 4:return f=X(),e.flags|=f,0;case 5:return f=X(),qa[f+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return L[cb()>>2]=28,-1;default:return-28}}catch(g){if("undefined"==typeof U||!(g instanceof U.g))throw g;return-g.v}},__syscall_getcwd:function(a,b){try{if(0===b)return-28;var d=U.cwd(),e=oa(d)+1;if(b<e)return-68;
H(d,K,a,b);return e}catch(f){if("undefined"==typeof U||!(f instanceof U.g))throw f;return-f.v}},__syscall_ioctl:function(a,b,d){W=d;try{var e=Y(a);switch(b){case 21509:case 21505:return e.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return e.tty?0:-59;case 21519:if(!e.tty)return-59;var f=X();return L[f>>2]=0;case 21520:return e.tty?-28:-59;case 21531:return f=X(),U.va(e,b,f);case 21523:return e.tty?0:-59;case 21524:return e.tty?0:-59;default:return-28}}catch(g){if("undefined"==
typeof U||!(g instanceof U.g))throw g;return-g.v}},__syscall_openat:function(a,b,d,e){W=e;try{b=b?G(K,b):"";var f=b;if("/"===f.charAt(0))b=f;else{var g=-100===a?U.cwd():Y(a).path;if(0==f.length)throw new U.g(44);b=R(g+"/"+f)}var l=e?X():0;return U.open(b,d,l).fd}catch(p){if("undefined"==typeof U||!(p instanceof U.g))throw p;return-p.v}},_emscripten_get_now_is_monotonic:function(){return!0},abort:function(){F("")},emscripten_date_now:function(){return Date.now()},emscripten_get_now:Ta,emscripten_memcpy_big:function(a,
b,d){K.copyWithin(a,b,b+d)},emscripten_resize_heap:function(a){var b=K.length;a>>>=0;if(536870912<a)return!1;for(var d=1;4>=d;d*=2){var e=b*(1+.2/d);e=Math.min(e,a+100663296);var f=Math;e=Math.max(a,e);f=f.min.call(f,536870912,e+(65536-e%65536)%65536);a:{try{la.grow(f-pa.byteLength+65535>>>16);ra();var g=1;break a}catch(l){}g=void 0}if(g)return!0}return!1},environ_get:function(a,b){var d=0;Va().forEach(function(e,f){var g=b+d;f=M[a+4*f>>2]=g;for(g=0;g<e.length;++g)J[f++>>0]=e.charCodeAt(g);J[f>>0]=
0;d+=e.length+1});return 0},environ_sizes_get:function(a,b){var d=Va();M[a>>2]=d.length;var e=0;d.forEach(function(f){e+=f.length+1});M[b>>2]=e;return 0},exit:Xa,fd_close:function(a){try{var b=Y(a);U.close(b);return 0}catch(d){if("undefined"==typeof U||!(d instanceof U.g))throw d;return d.v}},fd_read:function(a,b,d,e){try{a:{var f=Y(a);a=b;for(var g=b=0;g<d;g++){var l=M[a>>2],p=M[a+4>>2];a+=8;var q=U.read(f,J,l,p,void 0);if(0>q){var m=-1;break a}b+=q;if(q<p)break}m=b}M[e>>2]=m;return 0}catch(n){if("undefined"==
typeof U||!(n instanceof U.g))throw n;return n.v}},fd_seek:function(a,b,d,e,f){try{b=d+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*d:NaN;if(isNaN(b))return 61;var g=Y(a);U.C(g,b,e);Ea=[g.position>>>0,(Q=g.position,1<=+Math.abs(Q)?0<Q?(Math.min(+Math.floor(Q/4294967296),4294967295)|0)>>>0:~~+Math.ceil((Q-+(~~Q>>>0))/4294967296)>>>0:0)];L[f>>2]=Ea[0];L[f+4>>2]=Ea[1];g.sa&&0===b&&0===e&&(g.sa=null);return 0}catch(l){if("undefined"==typeof U||!(l instanceof U.g))throw l;return l.v}},fd_write:function(a,
b,d,e){try{a:{var f=Y(a);a=b;for(var g=b=0;g<d;g++){var l=M[a>>2],p=M[a+4>>2];a+=8;var q=U.write(f,J,l,p,void 0);if(0>q){var m=-1;break a}b+=q}m=b}M[e>>2]=m;return 0}catch(n){if("undefined"==typeof U||!(n instanceof U.g))throw n;return n.v}},strftime_l:function(a,b,d,e){return ab(a,b,d,e)}};
(function(){function a(f){c.asm=f.exports;la=c.asm.memory;ra();ta.unshift(c.asm.__wasm_call_ctors);za()}function b(f){a(f.instance)}function d(f){return Da().then(function(g){return WebAssembly.instantiate(g,e)}).then(function(g){return g}).then(f,function(g){D("failed to asynchronously prepare wasm: "+g);F(g)})}var e={env:db,wasi_snapshot_preview1:db};ya();if(c.instantiateWasm)try{return c.instantiateWasm(e,a)}catch(f){D("Module.instantiateWasm callback failed with error: "+f),k(f)}(function(){return E||
"function"!=typeof WebAssembly.instantiateStreaming||Aa()||A||"function"!=typeof fetch?d(b):fetch(P,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,e).then(b,function(g){D("wasm streaming compile failed: "+g);D("falling back to ArrayBuffer instantiation");return d(b)})})})().catch(k);return{}})();c.___wasm_call_ctors=function(){return(c.___wasm_call_ctors=c.asm.__wasm_call_ctors).apply(null,arguments)};
c._main=function(){return(c._main=c.asm.__main_argc_argv).apply(null,arguments)};c._usi_command=function(){return(c._usi_command=c.asm.usi_command).apply(null,arguments)};var cb=c.___errno_location=function(){return(cb=c.___errno_location=c.asm.__errno_location).apply(null,arguments)};c._malloc=function(){return(c._malloc=c.asm.malloc).apply(null,arguments)};
var eb=c.stackSave=function(){return(eb=c.stackSave=c.asm.stackSave).apply(null,arguments)},fb=c.stackRestore=function(){return(fb=c.stackRestore=c.asm.stackRestore).apply(null,arguments)},Z=c.stackAlloc=function(){return(Z=c.stackAlloc=c.asm.stackAlloc).apply(null,arguments)};c.dynCall_jiji=function(){return(c.dynCall_jiji=c.asm.dynCall_jiji).apply(null,arguments)};c.dynCall_viijii=function(){return(c.dynCall_viijii=c.asm.dynCall_viijii).apply(null,arguments)};
c.dynCall_iiiiij=function(){return(c.dynCall_iiiiij=c.asm.dynCall_iiiiij).apply(null,arguments)};c.dynCall_iiiiijj=function(){return(c.dynCall_iiiiijj=c.asm.dynCall_iiiiijj).apply(null,arguments)};c.dynCall_iiiiiijj=function(){return(c.dynCall_iiiiiijj=c.asm.dynCall_iiiiiijj).apply(null,arguments)};
c.ccall=function(a,b,d,e){var f={string:m=>{var n=0;if(null!==m&&void 0!==m&&0!==m){var v=(m.length<<2)+1;n=Z(v);H(m,K,n,v)}return n},array:m=>{var n=Z(m.length);J.set(m,n);return n}};a=c["_"+a];var g=[],l=0;if(e)for(var p=0;p<e.length;p++){var q=f[d[p]];q?(0===l&&(l=eb()),g[p]=q(e[p])):g[p]=e[p]}d=a.apply(null,g);return d=function(m){0!==l&&fb(l);return"string"===b?m?G(K,m):"":"boolean"===b?!!m:m}(d)};c.FS=U;var gb;O=function ib(){gb||jb();gb||(O=ib)};
function kb(a){var b=c._main;a=a||[];a.unshift(t);var d=a.length,e=Z(4*(d+1)),f=e>>2;a.forEach(l=>{var p=L,q=f++,m=oa(l)+1,n=Z(m);H(l,J,n,m);p[q]=n});L[f]=0;try{var g=b(d,e);Xa(g,!0)}catch(l){l instanceof ja||"unwind"==l||da(1,l)}}
function jb(){function a(){if(!gb&&(gb=!0,c.calledRun=!0,!ma)){c.noFSInit||U.ea.ua||U.ea();U.Va=!1;Fa(ta);Fa(ua);aa(c);if(c.onRuntimeInitialized)c.onRuntimeInitialized();lb&&kb(b);if(c.postRun)for("function"==typeof c.postRun&&(c.postRun=[c.postRun]);c.postRun.length;){var d=c.postRun.shift();va.unshift(d)}Fa(va)}}var b=b||ca;if(!(0<N)){if(c.preRun)for("function"==typeof c.preRun&&(c.preRun=[c.preRun]);c.preRun.length;)wa();Fa(sa);0<N||(c.setStatus?(c.setStatus("Running..."),setTimeout(function(){setTimeout(function(){c.setStatus("")},
1);a()},1)):a())}}if(c.preInit)for("function"==typeof c.preInit&&(c.preInit=[c.preInit]);0<c.preInit.length;)c.preInit.pop()();var lb=!0;c.noInitialRun&&(lb=!1);jb();


  return YaneuraOu_sse42.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = YaneuraOu_sse42;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return YaneuraOu_sse42; });
else if (typeof exports === 'object')
  exports["YaneuraOu_sse42"] = YaneuraOu_sse42;
