export const APP_STORAGE_KEY = "gunjin-shogi-v1";
export const APP_SCHEMA_VERSION = 2;

export const SIDES = {
  PLAYER: "player",
  AI: "ai",
};

export const SIDE_LABELS = {
  [SIDES.PLAYER]: "自分",
  [SIDES.AI]: "AI",
};

export const GAME_PHASES = {
  SETUP: "setup",
  BATTLE: "battle",
  FINISHED: "finished",
};

export const DIFFICULTIES = {
  easy: {
    id: "easy",
    label: "初級",
    samples: 6,
    depth: 1,
    threatDepth: 1,
    maxMillis: 120,
    moveLimit: 8,
    noise: 18,
  },
  medium: {
    id: "medium",
    label: "中級",
    samples: 12,
    depth: 2,
    threatDepth: 2,
    maxMillis: 280,
    moveLimit: 8,
    noise: 11,
  },
  hard: {
    id: "hard",
    label: "上級",
    samples: 32,
    depth: 3,
    threatDepth: 4,
    maxMillis: 1200,
    moveLimit: 12,
    noise: 3,
  },
};

const OFFICER_TOKEN_VISUALS = Object.freeze({
  marshal: Object.freeze({ type: "officer", officerClass: "general", stars: 3 }),
  general: Object.freeze({ type: "officer", officerClass: "general", stars: 2 }),
  brigadier: Object.freeze({ type: "officer", officerClass: "general", stars: 1 }),
  colonel: Object.freeze({ type: "officer", officerClass: "senior", stars: 3 }),
  lieutenantColonel: Object.freeze({ type: "officer", officerClass: "senior", stars: 2 }),
  major: Object.freeze({ type: "officer", officerClass: "senior", stars: 1 }),
  captain: Object.freeze({ type: "officer", officerClass: "junior", stars: 3 }),
  lieutenant: Object.freeze({ type: "officer", officerClass: "junior", stars: 2 }),
  secondLieutenant: Object.freeze({ type: "officer", officerClass: "junior", stars: 1 }),
});

export const PIECE_DEFS = {
  marshal: {
    type: "marshal",
    label: "大将",
    short: "大",
    count: 1,
    strength: 9,
    category: "rank",
    movable: true,
    hqVictoryEligible: true,
    value: 120,
    tokenVisual: OFFICER_TOKEN_VISUALS.marshal,
  },
  general: {
    type: "general",
    label: "中将",
    short: "中",
    count: 1,
    strength: 8,
    category: "rank",
    movable: true,
    hqVictoryEligible: true,
    value: 100,
    tokenVisual: OFFICER_TOKEN_VISUALS.general,
  },
  brigadier: {
    type: "brigadier",
    label: "少将",
    short: "少",
    count: 1,
    strength: 7,
    category: "rank",
    movable: true,
    hqVictoryEligible: true,
    value: 82,
    tokenVisual: OFFICER_TOKEN_VISUALS.brigadier,
  },
  colonel: {
    type: "colonel",
    label: "大佐",
    short: "大",
    count: 1,
    strength: 6,
    category: "rank",
    movable: true,
    hqVictoryEligible: true,
    value: 68,
    tokenVisual: OFFICER_TOKEN_VISUALS.colonel,
  },
  lieutenantColonel: {
    type: "lieutenantColonel",
    label: "中佐",
    short: "中",
    count: 1,
    strength: 5,
    category: "rank",
    movable: true,
    hqVictoryEligible: true,
    value: 58,
    tokenVisual: OFFICER_TOKEN_VISUALS.lieutenantColonel,
  },
  major: {
    type: "major",
    label: "少佐",
    short: "少",
    count: 1,
    strength: 4,
    category: "rank",
    movable: true,
    hqVictoryEligible: true,
    value: 50,
    tokenVisual: OFFICER_TOKEN_VISUALS.major,
  },
  captain: {
    type: "captain",
    label: "大尉",
    short: "大",
    count: 2,
    strength: 3,
    category: "rank",
    movable: true,
    hqVictoryEligible: false,
    value: 32,
    tokenVisual: OFFICER_TOKEN_VISUALS.captain,
  },
  lieutenant: {
    type: "lieutenant",
    label: "中尉",
    short: "中",
    count: 2,
    strength: 2,
    category: "rank",
    movable: true,
    hqVictoryEligible: false,
    value: 24,
    tokenVisual: OFFICER_TOKEN_VISUALS.lieutenant,
  },
  secondLieutenant: {
    type: "secondLieutenant",
    label: "少尉",
    short: "少",
    count: 2,
    strength: 1,
    category: "rank",
    movable: true,
    hqVictoryEligible: false,
    value: 18,
    tokenVisual: OFFICER_TOKEN_VISUALS.secondLieutenant,
  },
  cavalry: {
    type: "cavalry",
    label: "騎兵",
    short: "騎",
    count: 1,
    category: "special",
    movable: true,
    hqVictoryEligible: false,
    value: 22,
  },
  spy: {
    type: "spy",
    label: "スパイ",
    short: "諜",
    count: 1,
    category: "special",
    movable: true,
    hqVictoryEligible: false,
    value: 20,
  },
  flag: {
    type: "flag",
    label: "軍旗",
    short: "旗",
    count: 1,
    category: "special",
    movable: false,
    hqVictoryEligible: false,
    value: 34,
  },
  mine: {
    type: "mine",
    label: "地雷",
    short: "雷",
    count: 2,
    category: "special",
    movable: false,
    hqVictoryEligible: false,
    value: 20,
  },
  engineer: {
    type: "engineer",
    label: "工兵",
    short: "工",
    count: 2,
    category: "special",
    movable: true,
    hqVictoryEligible: false,
    value: 26,
  },
  tank: {
    type: "tank",
    label: "タンク",
    short: "戦",
    count: 2,
    category: "special",
    movable: true,
    hqVictoryEligible: false,
    value: 44,
  },
  aircraft: {
    type: "aircraft",
    label: "飛行機",
    short: "飛",
    count: 2,
    category: "special",
    movable: true,
    hqVictoryEligible: false,
    value: 54,
  },
};

export const PIECE_TYPES = Object.freeze(Object.keys(PIECE_DEFS));

export const IMMOBILE_TYPES = new Set(["flag", "mine"]);
export const GENERAL_TYPES = new Set(["marshal", "general", "brigadier"]);
export const HQ_VICTORY_ELIGIBLE_TYPES = new Set(
  PIECE_TYPES.filter((type) => PIECE_DEFS[type].hqVictoryEligible),
);

export const RANK_STRENGTH_TYPES = PIECE_TYPES.filter(
  (type) => PIECE_DEFS[type].category === "rank",
);

export const PRESET_LAYOUTS = {
  balanced: {
    id: "balanced",
    label: "標準",
    placements: {
      A6: "colonel",
      B6: "captain",
      C6: "tank",
      D6: "lieutenantColonel",
      E6: "captain",
      F6: "flag",
      A7: "engineer",
      B7: "cavalry",
      C7: "spy",
      D7: "marshal",
      E7: "engineer",
      F7: "aircraft",
      A8: "major",
      B8: "general",
      C8: "lieutenant",
      D8: "lieutenant",
      E8: "tank",
      F8: "mine",
      A9: "aircraft",
      B9: "secondLieutenant",
      HQ_P: "mine",
      E9: "secondLieutenant",
      F9: "brigadier",
    },
  },
  assault: {
    id: "assault",
    label: "速攻",
    placements: {
      A6: "tank",
      B6: "secondLieutenant",
      C6: "marshal",
      D6: "tank",
      E6: "lieutenantColonel",
      F6: "engineer",
      A7: "lieutenant",
      B7: "captain",
      C7: "major",
      D7: "spy",
      E7: "general",
      F7: "lieutenant",
      A8: "cavalry",
      B8: "engineer",
      C8: "captain",
      D8: "mine",
      E8: "flag",
      F8: "aircraft",
      A9: "secondLieutenant",
      B9: "aircraft",
      HQ_P: "mine",
      E9: "brigadier",
      F9: "colonel",
    },
  },
  fortress: {
    id: "fortress",
    label: "堅陣",
    placements: {
      A6: "engineer",
      B6: "brigadier",
      C6: "tank",
      D6: "secondLieutenant",
      E6: "lieutenant",
      F6: "colonel",
      A7: "captain",
      B7: "lieutenant",
      C7: "flag",
      D7: "spy",
      E7: "mine",
      F7: "tank",
      A8: "cavalry",
      B8: "general",
      C8: "mine",
      D8: "aircraft",
      E8: "lieutenantColonel",
      F8: "aircraft",
      A9: "captain",
      B9: "secondLieutenant",
      HQ_P: "marshal",
      E9: "major",
      F9: "engineer",
    },
  },
};

export const GUIDE_OVERVIEW_SECTIONS = [
  {
    title: "勝ち方",
    body:
      "敵司令部には全ての可動駒が入れますが、勝ちになるのは【大将】【中将】【少将】【大佐】【中佐】【少佐】で占領した時だけです。相手の動ける駒を全滅させても勝ちです。",
  },
  {
    title: "戦闘と推理",
    body:
      "敵駒の正体は隠されています。移動の仕方や勝敗から、相手の陣形と役割を推理して進めます。",
  },
  {
    title: "特殊なコマ：軍旗と地雷",
    body:
      "【軍旗】は直後方の味方駒と同じ強さになります。【地雷】は【工兵】【飛行機】以外の駒に攻撃されると爆発し、双方の駒が消えます。",
  },
  {
    title: "初期配置の作り方",
    body:
      "駒をドラッグ&ドロップで入れ替えて初期配置（陣形）をカスタマイズできます。迷った時は、デフォルトの陣形や「陣形サンプル」のものを採用するのもおすすめです。",
  },
];
